  CpuUsageAlarm: 

    Type: AWS::CloudWatch::Alarm 

    Properties: 

      AlarmName: 'CpuUsageAlarm' 

      ComparisonOperator: GreaterThanThreshold 

      EvaluationPeriods: '1' 

      MetricName: 'CPUUtilization' 

      Namespace: 'AWS/EC2' 

      Period: '300' 

      Statistic: 'Average' 

      Threshold: '80' 

      AlarmActions: 

        - 'arn:aws:sns:REGION:ACCOUNT_ID:MySNSAlarmTopic' 

      Dimensions: 

        - Name: 'InstanceId' 

          Value: !Ref NodeAppInstanceId 